networks:
  mysql_connector:
    driver: bridge

services:
  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin_ui
    networks:
      - mysql_connector
    environment:
      PMA_HOST: azdb-koiauction.mysql.database.azure.com
      PMA_PORT: 3306
      PMA_USER: lcaohoanq
      PMA_PASSWORD: 8N3v6'Z}=v$0
      PMA_SSL: require
    ports:
      - "81:80"                                           # Expose phpMyAdmin on port 81

volumes:
  mysql_data:
    driver: local