name: CI-Integration-Test for Koi-Auction-BE

on:
  push:
    branches: [ "develop", "test/unit-test" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: lcaohoanq/koiauction_on_ci:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Luucaohoang1604^^
          MYSQL_DATABASE: koi_company_dev_db
          MYSQL_USER: lcaohoanq
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h127.0.0.1 -uroot -pLuucaohoang1604^^ --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run All Integration Tests
        run: mvn -B clean verify --file pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/koi_company_dev_db
          SPRING_DATASOURCE_USERNAME: lcaohoanq
          SPRING_DATASOURCE_PASSWORD: Luucaohoang1604^^
          SPRING_PROFILES_ACTIVE: dev